name: A workflow for my Hello World file
on: push
<<<<<<< HEAD
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
=======
>>>>>>> 0190fb7bf547861b0076a06464ce1146fba34d8d
